spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: binarfud
          uri: http://localhost:8081
          predicates: 
            - Path=/api/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka